package settlements

var (
	SettSizes = []int{
		500,
		600,
		700,
		750,
		800,
		825,
		900,
		1000,
		6000,
		8000,
		10000,
		12000,
		16000,
		18000,
		22500,
		25000,
		30000,
		50000,
		90000,
		100000,
		250000,
	}
	SettGovenments = []string{
		"Autocracy",
		"Bureaucracy",
		"Confederacy",
		"Democracy",
		"Dictatorship",
		"Feudalism",
		"Gerontocracy",
		"Hierarchy",
		"Magocracy",
		"Matriarchy",
		"Militoctracy",
		"Monarchy",
		"Oligarchy",
		"Patriarchy",
		"Plutocracy",
		"Republic",
		"Satrapy",
		"Kleptocracy",
		"Theocracy",
		"Technocracy",
	}
	SettGeographies = []string{
		"River Delta",
		"Mountain Pass",
		"Volcanic Plain",
		"Desert Oasis",
		"Floodplain",
		"Cliffside Terrace",
		"Valley Floor",
		"Swamp Basin",
		"Tundra Shelf",
		"Jungle Canopy Plateau",
		"Cave System Entrance",
		"Highland Ridge",
		"Coastal Bluff",
		"Salt Flat",
		"Forest Glade",
		"Canyon Ledge",
		"Steppe Frontier",
		"Lakeside",
		"Wind-Swept Moor",
	}
	SettAtmospheres = []string{
		"Bustling market chatter",
		"Smoke-hazed rooftops",
		"Lantern-lit alleys",
		"Watchful, narrow streets",
		"Rain-slick cobblestones",
		"Dust-blown silence",
		"Chime-filled courtyards",
		"Woodsmoke and laughter",
		"Wary eyes watching",
		"Twilight-wrapped towers",
		"Broken walls breathing",
		"Verdant stonework peace",
		"Rancid fish stench",
		"Gutter-whispered secrets",
		"Church bells echoing",
		"Torches flare warmly",
		"Mud-stained footpaths",
		"Crowded with voices",
		"Crickets over stillness",
		"Tense with memory",
	}
	SettCharacters = []string{
		"Built atop ancient bones",
		"Traders never speak names",
		"Rain falls upward here",
		"Giant mushrooms line streets",
		"Haunted bells ring nightly",
		"Sunlight never reaches ground",
		"Everyone wears bird masks",
		"Stone buildings hum softly",
		"Dreams dictate daily law",
		"Time runs faster inside",
		"Only children hold power",
		"Wind always blows eastward",
		"Lanterns float without flame",
		"No one leaves after dusk",
		"Built in a crater",
		"Voices echo before speaking",
		"Wolves walk among townsfolk",
		"Water tastes like honey",
		"Memories fade at gates",
		"All roads circle inward",
	}
	SettAmeniities = []string{
		"Library",
		"Apothecary",
		"Blacksmith",
		"Tavern",
		"Inn",
		"Mapmaker",
		"Weapons Master",
		"Enchanter",
		"Magic Trinkets",
		"Stables",
		"Alchemist",
		"Curiosities",
		"Temple",
		"Healer",
		"Pawnshop",
		"Scriptorium",
		"Bounty Board",
		"Wagonwright",
		"Jeweler",
		"Underground Fighting",
	}
	SettNames = []string{
		"Briarhold",
		"Ashfen Cross",
		"Duskwatch",
		"Marrowdeep",
		"Hearthmere",
		"Stonehollow",
		"Viremoor",
		"Thistlewake",
		"Cragspire",
		"Ebonreach",
		"Willowrest",
		"Gravethorn",
		"Frostmere",
		"Sunthistle Downs",
		"Rimefort",
		"Driftchapel",
		"Lanternrock",
		"Wyrmgate",
		"Silvergrove",
		"Oathridge",
	}
)
